name: omnispace
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  geolocator: ^11.0.0
  linkpeek: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  any_link_preview: ^3.0.1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/omnispace.png"

flutter:
  uses-material-design: true
  assets:
    - assets/omnispace.png
